### ISSUE TITLE
`posix_spawnp: does not exist`

### ISSUE THREAD

**Issue by PiotrJustyna** [juhp/simple-cmd#1]
Hello,

First of all, thank you for putting the library together. Really nice work 👏 Having a problem with the lib while using it in a devcontainer, I wonder if I am missing some dependencies/configuration?

```
[vscode@55c42eddd75a osmium]$ stack exec osmium-exe
osmium-exe: aws lambda list-functions: readCreateProcess: posix_spawnp: does not exist (No such file or directory)
```

Here's the project I am using this in: https://github.com/PiotrJustyna/osmium

**Comment by juhp** [comment]
Okay I think the error message (which comes from `process`) may be confusing you:

I think it is just telling you that the `aws` command is not found

(I have tried to look into fixing this - it is deep in ghc, but it is still open unfortunately - I can dig out the ticket if you are interested and there are other examples of these poor error messages unfortunately)

**Comment by juhp** [comment]
Ah nvm what i wrote: okay that is incorrect usage - you want:

`cmd "aws" ["lambda", "list-functions"]`

or if you really want to call out to shell (discouraged): `shell "aws lambda list-functions"`

**Comment by PiotrJustyna** [comment]
Just double checked, the command is working. Thanks!
